# Generated by Django 4.2.19 on 2025-03-08 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GCOP_', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationships',
            fields=[
                ('relationship_id', models.AutoField(primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'relationships',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='churchpositions',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='joinedgroups',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='relations',
            options={'managed': False},
        ),
    ]
