# Generated by Django 4.2.19 on 2025-03-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GCOP_', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_image',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
