# Generated by Django 5.1.7 on 2025-03-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GCOP_', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_printed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
