# Generated by Django 5.1.7 on 2025-04-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GCOP_', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='church_id',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
