# Generated by Django 5.1.7 on 2025-03-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GCOP_', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='nxt_of_kin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
