# Generated by Django 5.1.7 on 2025-03-30 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GCOP_', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'managed': True},
        ),
    ]
