# Generated by Django 4.2.19 on 2025-03-03 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GCOP_', '0002_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branches',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='groups',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='joinedgroups',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='positions',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='relations',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='relationships',
            options={'managed': True},
        ),
    ]
