# Generated by Django 5.1.7 on 2025-03-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GCOP_', '0002_member_is_printed'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='dues_card_num',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
