# Generated by Django 4.2.19 on 2025-03-08 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GCOP_', '0002_relationships_alter_churchpositions_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='churchpositions',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'managed': True},
        ),
    ]
