# Generated by Django 4.2.19 on 2025-03-03 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GCOP_', '0003_alter_branches_options_alter_groups_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinedgroups',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='GCOP_.groups'),
        ),
        migrations.AddField(
            model_name='joinedgroups',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='GCOP_.member'),
        ),
        migrations.AddField(
            model_name='joinedgroups',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='GCOP_.positions'),
        ),
        migrations.AddField(
            model_name='member',
            name='church_branch',
            field=models.ForeignKey(blank=True, db_column='church_branch', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='GCOP_.branches'),
        ),
        migrations.AddField(
            model_name='relations',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='GCOP_.member'),
        ),
        migrations.AddField(
            model_name='relations',
            name='relationship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='GCOP_.relationships'),
        ),
    ]
