# Generated by Django 4.2.19 on 2025-03-06 17:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GCOP_', '0003_alter_member_member_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
