# Generated by Django 5.1.7 on 2025-03-20 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GCOP_', '0003_member_dues_card_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='dues_card_num',
            new_name='place_of_residence',
        ),
    ]
