# Generated by Django 4.2.19 on 2025-03-03 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GCOP_', '0004_joinedgroups_group_joinedgroups_member_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='joinedgroups',
            table='joinedGroups',
        ),
    ]
