# Generated by Django 5.1.7 on 2025-03-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GCOP_', '0004_rename_dues_card_num_member_place_of_residence'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='registered_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
