# Generated by Django 5.1.7 on 2025-03-30 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GCOP_', '0005_alter_member_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'managed': True},
        ),
    ]
