# Generated by Django 5.1.7 on 2025-03-30 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GCOP_', '0006_alter_member_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'managed': False},
        ),
    ]
