# Generated by Django 5.1.7 on 2025-03-31 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GCOP_', '0007_alter_member_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gcop_id', models.CharField(blank=True, max_length=15, unique=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='GCOP_.member')),
            ],
        ),
    ]
