# Generated by Django 5.1.7 on 2025-04-02 14:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GCOP_', '0008_churchid'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceMercyTemple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'db_table': 'attendance_in_mercy_temple',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'managed': True},
        ),
    ]
